INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (1, 'Valinhos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (2, 'Americana', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (3, 'Santa Bárbara d''Oeste', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (4, 'Aguaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (5, 'Guarujá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (6, 'Sorocaba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (7, 'São Paulo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (8, 'Cosmópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (9, 'Taubaté', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (10, 'São Vicente', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (11, 'Itu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (12, 'Barueri', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (13, 'Matão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (14, 'Franca', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (15, 'Osasco', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (16, 'Piracicaba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (17, 'Santos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (18, 'Bauru', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (19, 'Guarulhos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (20, 'Atibaia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (21, 'Praia Grande', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (22, 'Santo André', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (23, 'São Bernardo do Campo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (24, 'Ribeirão Preto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (25, 'Presidente Prudente', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (26, 'Capão Bonito', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (27, 'São José dos Campos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (28, 'Carapicuíba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (29, 'Porto Feliz', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (30, 'Campinas', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (31, 'Mauá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (32, 'Rio das Pedras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (33, 'Paulínia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (34, 'Poá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (35, 'Santana de Parnaíba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (36, 'Diadema', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (37, 'Rio Claro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (38, 'Assis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (39, 'São João da Boa Vista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (40, 'São Caetano do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (41, 'Jundiaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (42, 'Taboão da Serra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (43, 'São José do Rio Preto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (44, 'Mairinque', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (45, 'Itapetininga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (46, 'Sumaré', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (47, 'São Carlos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (48, 'Araraquara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (49, 'Jacareí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (50, 'Suzano', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (51, 'Tapiratiba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (52, 'Limeira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (53, 'Birigui', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (54, 'Itapevi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (55, 'Lorena', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (56, 'Aparecida', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (57, 'São Sebastião', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (58, 'Botucatu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (59, 'Jaú', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (60, 'Santa Maria da Serra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (61, 'Sertãozinho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (62, 'Bebedouro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (63, 'Avaré', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (64, 'Garça', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (65, 'São Miguel Arcanjo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (66, 'Cravinhos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (67, 'Cotia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (68, 'Araçatuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (69, 'Tietê', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (70, 'Pederneiras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (71, 'Mogi Guaçu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (72, 'Votorantim', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (73, 'Orlândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (74, 'Barretos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (75, 'Itapeva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (76, 'Ubatuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (77, 'Marília', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (78, 'Ourinhos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (79, 'Itanhaém', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (80, 'Itararé', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (81, 'Américo Brasiliense', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (82, 'Orindiúva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (83, 'Paulo de Faria', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (84, 'Campos do Jordão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (85, 'Mococa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (86, 'Martinópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (87, 'Penápolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (88, 'Santa Cruz do Rio Pardo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (89, 'Bragança Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (90, 'Embu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (91, 'Mogi das Cruzes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (92, 'Capivari', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (93, 'Itápolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (94, 'Ibitinga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (95, 'José Bonifácio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (96, 'Colina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (97, 'Leme', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (98, 'Pindamonhangaba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (99, 'Mirassol', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (100, 'Caraguatatuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (101, 'Itatiba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (102, 'Pirassununga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (103, 'São José do Rio Pardo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (104, 'Potim', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (105, 'Guaratinguetá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (106, 'Nova Odessa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (107, 'Bocaina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (108, 'Hortolândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (109, 'Serra Negra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (110, 'Ilha Comprida', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (111, 'Águas de São Pedro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (112, 'Cabreúva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (113, 'Francisco Morato', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (114, 'Bofete', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (115, 'Boracéia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (116, 'Fartura', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (117, 'Serra Azul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (118, 'Araras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (119, 'Lavínia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (120, 'Paraibuna', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (121, 'Bom Jesus dos Perdões', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (122, 'Votuporanga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (123, 'Várzea Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (124, 'Novo Horizonte', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (125, 'Ibaté', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (126, 'Campo Limpo Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (127, 'São Roque', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (128, 'Itupeva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (129, 'Franco da Rocha', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (130, 'Rinópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (131, 'Juquitiba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (132, 'Cubatão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (133, 'Andradina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (134, 'Mogi Mirim', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (135, 'Lençóis Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (136, 'Sandovalina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (137, 'Taquaritinga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (138, 'Catanduva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (139, 'Olímpia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (140, 'Indaiatuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (141, 'Pinhalzinho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (142, 'Monte Mor', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (143, 'Conchal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (144, 'Itariri', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (145, 'Torrinha', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (146, 'Santa Cruz da Conceição', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (147, 'Guará', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (148, 'Ipuã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (149, 'Barbosa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (150, 'Vinhedo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (151, 'Iguape', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (152, 'Mirante do Paranapanema', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (153, 'Mombuca', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (154, 'Urupês', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (155, 'Louveira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (156, 'Alfredo Marcondes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (157, 'Rosana', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (158, 'Itapecerica da Serra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (159, 'Valentim Gentil', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (160, 'Santa Mercedes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (161, 'Caçapava', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (162, 'Macatuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (163, 'Dois Córregos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (164, 'Pedrinhas Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (165, 'Dourado', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (166, 'Saltinho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (167, 'Álvares Machado', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (168, 'Presidente Epitácio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (169, 'Jales', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (170, 'Monte Aprazível', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (171, 'Pedreira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (172, 'Monte Azul Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (173, 'Ribeirão Pires', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (174, 'Ilhabela', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (175, 'Presidente Venceslau', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (176, 'Fernandópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (177, 'Caiuá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (178, 'Maracaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (179, 'Laranjal Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (180, 'Engenheiro Coelho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (181, 'Cordeirópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (182, 'Pereiras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (183, 'Arealva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (184, 'Altair', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (185, 'Batatais', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (186, 'Taquarituba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (187, 'Piraju', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (188, 'Bernardino de Campos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (189, 'Barra Bonita', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (190, 'Santo Antônio de Posse', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (191, 'Santa Cruz das Palmeiras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (192, 'Adamantina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (193, 'Pontal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (194, 'Piracaia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (195, 'Jaboticabal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (196, 'Miracatu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (197, 'Jardinópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (198, 'Itaquaquecetuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (199, 'Santa Fé do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (200, 'Dracena', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (201, 'Junqueirópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (202, 'Regente Feijó', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (203, 'Duartina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (204, 'Santa Albertina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (205, 'Lins', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (206, 'Presidente Alves', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (207, 'Ribeira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (208, 'Serrana', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (209, 'Cajamar', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (210, 'Rancharia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (211, 'Boituva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (212, 'Panorama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (213, 'Tremembé', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (214, 'Mairiporã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (215, 'Osvaldo Cruz', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (216, 'Severínia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (217, 'Jaguariúna', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (218, 'Itapira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (219, 'Paraguaçu Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (220, 'Vargem Grande Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (221, 'Arapeí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (222, 'Jandira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (223, 'Piedade', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (224, 'Palmital', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (225, 'Tambaú', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (226, 'São Sebastião da Grama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (227, 'Ferraz de Vasconcelos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (228, 'Brotas', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (229, 'Canitar', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (230, 'Santópolis do Aguapeí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (231, 'Agudos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (232, 'Guaíra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (233, 'Tanabi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (234, 'Catiguá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (235, 'Quatá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (236, 'Monções', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (237, 'Floreal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (238, 'Sebastianópolis do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (239, 'Casa Branca', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (240, 'Caieiras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (241, 'Borborema', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (242, 'Urânia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (243, 'Salto de Pirapora', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (244, 'Pariquera-Açu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (245, 'Nova Campina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (246, 'Apiaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (247, 'Jacupiranga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (248, 'Glicério', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (249, 'Nuporanga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (250, 'Itaporanga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (251, 'Guaraçaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (252, 'Lucélia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (253, 'Terra Roxa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (254, 'Registro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (255, 'Pirapozinho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (256, 'Iacri', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (257, 'Iracemápolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (258, 'Cândido Mota', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (259, 'Salto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (260, 'Nova Europa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (261, 'Tupã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (262, 'Cananéia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (263, 'Santo Antônio da Alegria', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (264, 'Paraíso', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (265, 'Avaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (266, 'Boa Esperança do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (267, 'Pompéia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (268, 'Buritama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (269, 'Planalto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (270, 'Tatuí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (271, 'Valparaíso', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (272, 'Arujá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (273, 'Sales Oliveira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (274, 'Ituverava', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (275, 'Itaberá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (276, 'Manduri', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (277, 'Santo Anastácio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (278, 'Santo Expedito', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (279, 'Araçariguama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (280, 'Pitangueiras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (281, 'Barrinha', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (282, 'Herculândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (283, 'São Manuel', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (284, 'Analândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (285, 'Santa Rita do Passa Quatro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (286, 'Caconde', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (287, 'Pradópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (288, 'Flórida Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (289, 'Porto Ferreira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (290, 'Alumínio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (291, 'São Pedro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (292, 'Teodoro Sampaio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (293, 'Pedregulho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (294, 'Altinópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (295, 'Piratininga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (296, 'Auriflama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (297, 'Amparo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (298, 'Peruíbe', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (299, 'Ilha Solteira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (300, 'Ribeirão Branco', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (301, 'Guapiara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (302, 'Vargem Grande do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (303, 'Tarabai', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (304, 'Estrela do Norte', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (305, 'Bento de Abreu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (306, 'Avanhandava', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (307, 'Espírito Santo do Pinhal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (308, 'Salmourão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (309, 'Divinolândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (310, 'Piquete', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (311, 'Bady Bassitt', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (312, 'São Luís do Paraitinga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (313, 'Pilar do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (314, 'Marapoama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (315, 'Ariranha', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (316, 'Santo Antônio do Aracanguá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (317, 'Zacarias', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (318, 'Itapuí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (319, 'Charqueada', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (320, 'Chavantes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (321, 'Espírito Santo do Turvo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (322, 'Descalvado', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (323, 'Icém', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (324, 'Vera Cruz', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (325, 'Itaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (326, 'São Pedro do Turvo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (327, 'Alto Alegre', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (328, 'Pontes Gestal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (329, 'Itatinga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (330, 'Igaraçu do Tietê', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (331, 'Guararapes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (332, 'General Salgado', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (333, 'Guaimbê', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (334, 'Barra do Turvo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (335, 'Taquarivaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (336, 'Ibiúna', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (337, 'Capela do Alto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (338, 'Campos Novos Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (339, 'Itajobi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (340, 'Santa Adélia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (341, 'Rafard', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (342, 'Promissão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (343, 'Cerquilho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (344, 'Alambari', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (345, 'Coronel Macedo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (346, 'Américo de Campos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (347, 'São João das Duas Pontes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (348, 'Pereira Barreto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (349, 'Sete Barras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (350, 'Iperó', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (351, 'Reginópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (352, 'Cafelândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (353, 'Bariri', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (354, 'Cajuru', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (355, 'Patrocínio Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (356, 'Ribeirão do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (357, 'Cerqueira César', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (358, 'Queluz', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (359, 'Elias Fausto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (360, 'Uchoa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (361, 'Iacanga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (362, 'São Lourenço da Serra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (363, 'Santa Isabel', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (364, 'Rincão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (365, 'Cássia dos Coqueiros', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (366, 'Artur Nogueira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (367, 'Buri', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (368, 'Cachoeira Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (369, 'Estrela d''Oeste', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (370, 'Itirapina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (371, 'Morro Agudo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (372, 'Cruzeiro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (373, 'Bertioga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (374, 'Cristais Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (375, 'Castilho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (376, 'Sud Mennucci', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (377, 'Tupi Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (378, 'Ribeirão Bonito', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (379, 'Gália', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (380, 'Mineiros do Tietê', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (381, 'Salto Grande', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (382, 'Quintana', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (383, 'Tabatinga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (384, 'Restinga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (385, 'Taguaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (386, 'Cajobi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (387, 'Mirandópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (388, 'Mariápolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (389, 'Poloni', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (390, 'Jarinu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (391, 'Álvaro de Carvalho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (392, 'Florínia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (393, 'Igaratá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (394, 'Júlio Mesquita', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (395, 'Santa Gertrudes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (396, 'Conchas', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (397, 'Monte Alto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (398, 'Cabrália Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (399, 'São Simão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (400, 'Jeriquara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (401, 'Ocauçu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (402, 'Bastos', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (403, 'Álvares Florence', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (404, 'Tejupá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (405, 'Sales', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (406, 'Narandiba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (407, 'Mendonça', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (408, 'Morungaba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (409, 'Lavrinhas', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (410, 'Guariba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (411, 'Juquiá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (412, 'Ipaussu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (413, 'Iepê', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (414, 'Murutinga do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (415, 'Gavião Peixoto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (416, 'Itaóca', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (417, 'Holambra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (418, 'Echaporã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (419, 'Ubirajara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (420, 'Populina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (421, 'Brodowski', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (422, 'Embu-Guaçu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (423, 'Ipeúna', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (424, 'Sarapuí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (425, 'Cesário Lange', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (426, 'Nazaré Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (427, 'São Joaquim da Barra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (428, 'Mongaguá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (429, 'Angatuba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (430, 'Coroados', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (431, 'Santa Cruz da Esperança', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (432, 'Araçoiaba da Serra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (433, 'Tarumã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (434, 'Roseira', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (435, 'São José do Barreiro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (436, 'Eldorado', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (437, 'Miguelópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (438, 'Potirendaba', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (439, 'Jaci', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (440, 'Luiziânia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (441, 'Águas de Lindóia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (442, 'Onda Verde', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (443, 'Cândido Rodrigues', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (444, 'Paranapanema', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (445, 'Pirangi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (446, 'São José da Bela Vista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (447, 'Gastão Vidigal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (448, 'Lupércio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (449, 'Itobi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (450, 'Cedral', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (451, 'Nova Granada', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (452, 'Ibirá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (453, 'Colômbia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (454, 'Águas de Santa Bárbara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (455, 'Arandu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (456, 'Pindorama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (457, 'Ribeirão Corrente', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (458, 'Irapuã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (459, 'Socorro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (460, 'Guaraci', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (461, 'Presidente Bernardes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (462, 'Ubarana', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (463, 'Igarapava', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (464, 'Cunha', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (465, 'Viradouro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (466, 'Magda', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (467, 'Emilianópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (468, 'Sabino', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (469, 'Marinópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (470, 'Caiabu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (471, 'Três Fronteiras', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (472, 'Pirapora do Bom Jesus', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (473, 'Meridiano', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (474, 'Irapuru', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (475, 'Anhembi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (476, 'Canas', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (477, 'Lindóia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (478, 'Itaju', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (479, 'Palmares Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (480, 'Luís Antônio', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (481, 'Neves Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (482, 'Salesópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (483, 'Rubinéia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (484, 'Riolândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (485, 'Biritiba-Mirim', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (486, 'Bilac', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (487, 'Fernão', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (488, 'Taiaçu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (489, 'Nhandeara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (490, 'Ipiguá', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (491, 'Euclides da Cunha Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (492, 'Rio Grande da Serra', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (493, 'Santa Branca', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (494, 'CAMBUCI', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (495, 'SANTO AMARO', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (496, 'BOM RETIRO', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (497, 'Alvinlândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (498, 'Jambeiro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (499, 'Joanópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (500, 'Adolfo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (501, 'Inúbia Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (502, 'Bom Sucesso de Itararé', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (503, 'Brejo Alegre', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (504, 'Aramina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (505, 'Vitória Brasil', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (506, 'Parapuã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (507, 'Rifaina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (508, 'Santa Salete', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (509, 'Santo Antônio do Jardim', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (510, 'Santa Rita d''Oeste', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (511, 'Vista Alegre do Alto', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (512, 'Vargem', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (513, 'Taiúva', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (514, 'Óleo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (515, 'Cajati', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (516, 'Areias', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (517, 'Oriente', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (518, 'Bálsamo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (519, 'Estiva Gerbi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (520, 'João Ramalho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (521, 'Ibirarema', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (522, 'Guapiaçu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (523, 'Santa Rosa de Viterbo', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (524, 'Barra do Chapéu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (525, 'Nova Luzitânia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (526, 'União Paulista', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (527, 'Gabriel Monteiro', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (528, 'Tabapuã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (529, 'Palestina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (530, 'Oscar Bressane', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (531, 'Mirassolândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (532, 'Indiaporã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (533, 'Paranapuã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (534, 'Mira Estrela', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (535, 'Palmeira d''Oeste', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (536, 'Aparecida d''Oeste', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (537, 'Santana da Ponte Pensa', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (538, 'Pirajuí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (539, 'Santa Ernestina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (540, 'Pedra Bela', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (541, 'Guaiçara', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (542, 'Guararema', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (543, 'Piacatu', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (544, 'Sem Informação', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (545, 'Braúna', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (546, 'Monte Alegre do Sul', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (547, 'Nova Guataporanga', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (548, 'METRO ITAQUERA', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (549, 'ITAQUERA', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (550, 'Santa Lúcia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (551, 'Bananal', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (552, 'Nova Aliança', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (553, 'PRUDENTE"', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (554, 'Corumbataí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (555, 'Ouroeste', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (556, 'Cosmorama', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (557, 'Cardoso', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (558, 'Jaborandi', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (559, 'Paulicéia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (560, 'Jumirim', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (561, 'Guatapará', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (562, 'Monteiro Lobato', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (563, 'Pratânia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (564, 'Suzanápolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (565, 'Cruzália', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (566, 'Lucianópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (567, 'Mesópolis', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (568, 'Indiana', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (569, 'São Bento do Sapucaí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (570, 'Queiroz', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (571, 'Clementina', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (572, 'Pardinho', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (573, 'Ribeirão Grande', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (574, 'Nipoã', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (575, 'Guzolândia', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (576, 'Guareí', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (577, 'VILA ESPANHOLA', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (578, 'Fernando Prestes', 3);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (579, 'Nova Iguaçu', 5);
INSERT INTO public.tb_cidade (id, nome, estado_id) VALUES (580, 'Missuru', 8);